name: app

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/app.yaml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Getting source code
        uses: actions/checkout@v1

      - name: Use Node.js 12.18.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.1

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Caching
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: cd app && yarn install

      - name: Linting
        run: cd app && yarn lint

      - name: Test
        run: cd app && yarn test:unit
